### ISSUE TITLE
fdroidserver  build failed

### ISSUE THREAD

**Issue by QGB** [9Lukas5/AACPlayer#3]
`docker run -it -v /root/:/root/ -v/home/qgb/:/home/qgb/ 9lukas5/fdroidserver:1.0.11 bash           `

```
fdroid build

 OSError while trying to execute /usr/local/lib/python3.9/dist-packages/gradlew-fdroid clean: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/dist-packages/gradlew-fdroid'
2023-09-10 15:34:37,521 DEBUG: skip deploying full build logs: not enabled in config
2023-09-10 15:34:37,523 DEBUG: skip deploying full build logs: not enabled in config
2023-09-10 15:34:37,524 INFO: Finished
2023-09-10 15:34:37,524 INFO: 1 build failed
```

**Comment by 9Lukas5** [comment]
Closing as it's invalid here

The repo you searched for is here: https://gitlab.com/9l5/docker/fdroidserver/

But: don't bother opening a ticket there. This image is just thought to host already compiled apks, not to build apps from source. The image is just to basically have snapshots of the pypi fdroidserver binary in a ready to pull and run `fdroid update` form. Sorry.
